version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(gradle-deps)"
    versioning-strategy: increase
  - package-ecosystem: "gradle"
    directory: "/ultrasonic"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(gradle-deps)"
    versioning-strategy: increase
  - package-ecosystem: "gradle"
    directory: "/core/subsonic-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(gradle-deps)"
    versioning-strategy: increase
  - package-ecosystem: "gradle"
    directory: "/core/domain"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(gradle-deps)"
    versioning-strategy: increase
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(actions)"
    versioning-strategy: increase
