version: '3.8'

services:
  apk-hoster:
    image: ${DOCKER_IMAGE}:latest
    container_name: apk-hoster
    ports:
      - "8275:8275"
    volumes:
      - ${REMOTE_DIST_PATH}:/app/dist
    restart: always
