#!/bin/bash
set -e

# Configuration
APP_NAME="ultrasonic"
DIST_DIR="dist"
MODULE="ultrasonic"

echo "--- Starting publish of $APP_NAME ---"

# 1. Extract Version Info from build.gradle
echo "--- Extracting version info ---"
VERSION_NAME=$(grep "versionName" $MODULE/build.gradle | head -n 1 | sed 's/.*"\(.*\)".*/\1/' || echo "unknown")
VERSION_CODE=$(grep "versionCode" $MODULE/build.gradle | head -n 1 | sed 's/[^0-9]*//g' || echo "0")

# 2. Publish Artifacts to dist/
echo "--- Publishing Artifacts to $DIST_DIR ---"
mkdir -p "$DIST_DIR"

APK_PATH="$MODULE/build/outputs/apk/release/$MODULE-release.apk"
UNSIGNED_APK_PATH="$MODULE/build/outputs/apk/release/$MODULE-release-unsigned.apk"

if [ -f "$APK_PATH" ]; then
    DEST="$DIST_DIR/$APP_NAME-v$VERSION_NAME-$VERSION_CODE.apk"
    cp "$APK_PATH" "$DEST"
    echo "Successfully published: $DEST"
elif [ -f "$UNSIGNED_APK_PATH" ]; then
    DEST="$DIST_DIR/$APP_NAME-v$VERSION_NAME-$VERSION_CODE-unsigned.apk"
    cp "$UNSIGNED_APK_PATH" "$DEST"
    echo "Successfully published (UNSIGNED): $DEST"
    echo "Note: Configure signing in local.properties to produce signed release builds."
else
    echo "ERROR: Could not find resulting APK artifact. Did you run build.sh first?"
    exit 1
fi

# 3. Generate Index HTML for easy distribution
echo "--- Updating index.html ---"
cat > "$DIST_DIR/index.html" <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>$APP_NAME Downloads</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; background: #f4f7f9; color: #333; }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-bottom: 30px; }
        .apk-list { list-style: none; padding: 0; }
        .apk-item { margin-bottom: 15px; padding: 20px; border-radius: 12px; background: white; box-shadow: 0 4px 6px rgba(0,0,0,0.05); transition: transform 0.2s; border-left: 5px solid #3498db; }
        .apk-item:hover { transform: translateY(-2px); box-shadow: 0 6px 12px rgba(0,0,0,0.1); }
        .apk-link { font-weight: bold; font-size: 1.1em; text-decoration: none; color: #2980b9; display: block; word-break: break-all; }
        .apk-info { color: #7f8c8d; font-size: 0.85em; margin-top: 8px; display: flex; justify-content: space-between; }
        .tag { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; font-weight: bold; background: #e0e0e0; margin-left: 10px; }
        .tag-latest { background: #27ae60; color: white; }
    </style>
</head>
<body>
    <h1>$APP_NAME Downloads</h1>
    <ul class="apk-list">
EOF

# Use ls -t to sort by time, and loop through files
IS_FIRST=true
# Use a temporary file to avoid globbing issues in for loop if filenames have spaces
ls -t "$DIST_DIR"/*.apk > /tmp/apk_list.txt
while IFS= read -r apk; do
    [ -z "$apk" ] && continue
    filename=$(basename "$apk")
    filedate=$(date -r "$apk" "+%Y-%m-%d %H:%M")
    
    LATEST_TAG=""
    if [ "$IS_FIRST" = true ]; then
        LATEST_TAG="<span class='tag tag-latest'>LATEST</span>"
        IS_FIRST=false
    fi
    
    cat >> "$DIST_DIR/index.html" <<EOF
        <li class="apk-item">
            <a class="apk-link" href="$filename">$filename $LATEST_TAG</a>
            <div class="apk-info">
                <span>Built: $filedate</span>
                <span class="tag">APK</span>
            </div>
        </li>
EOF
done < /tmp/apk_list.txt

cat >> "$DIST_DIR/index.html" <<EOF
    </ul>
    <footer style="margin-top: 40px; text-align: center; color: #95a5a6; font-size: 0.8em;">
        <p>Generated by publish.sh on $(date "+%Y-%m-%d %H:%M:%S")</p>
    </footer>
</body>
</html>
EOF

# 4. Docker Publish (Optional)
DOCKER_IMAGE="tsshadow/apk-hoster"
if command -v docker >/dev/null 2>&1; then
    echo "--- Building Docker Image: $DOCKER_IMAGE ---"
    docker build -t "$DOCKER_IMAGE" -f apk-hoster/Dockerfile .
    
    echo "--- Pushing Docker Image: $DOCKER_IMAGE ---"
    docker push "$DOCKER_IMAGE"
else
    echo "Warning: docker command not found, skipping Docker build."
fi

echo "--- All publishes completed ---"
echo ""
echo "Quick Distribute: Run the following to host your APKs on your local network:"
echo "cd $DIST_DIR && python3 -m http.server 8080"
echo "Then visit http://$(hostname -I | awk '{print $1}'):8080 on your phone."
