

plugins {
    id("com.google.devtools.ksp") version "2.3.2"
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.serialization") version "1.9.23"
    id("kotlin-parcelize")
    id("androidx.navigation.safeargs.kotlin")
}

android {
    def signingProperties = new Properties()
    def localPropsFile = rootProject.file("local.properties")
    if (localPropsFile.exists()) {
        localPropsFile.withInputStream { signingProperties.load(it) }
    }

    def envOrProp = { String key, String defVal = null ->
        return System.getenv(key) ?: signingProperties.getProperty(key, defVal)
    }

    compileSdkVersion versions.compileSdk

    defaultConfig {
        applicationId "org.moire.ultrasonic"
        versionCode 130
        versionName "4.8.0"

        minSdkVersion versions.minSdk
        targetSdkVersion versions.targetSdk
        resourceConfigurations += ['cs', 'de', 'en', 'es', 'fr', 'gl', 'hu', 'it', 'ja', 'nb-rNO', 'nl', 'pl', 'pt', 'pt-rBR', 'ru', 'zh-rCN', 'zh-rTW']
    }

    bundle.language.enableSplit = false

    def storeLocation = envOrProp('SIGNING_STORE_FILE', rootProject.file('keystore.jks').path)
    File resolvedStoreFile = null
    if (storeLocation != null) {
        def candidate = new File(storeLocation)
        resolvedStoreFile = candidate.isAbsolute() ? candidate : rootProject.file(storeLocation)
    }

    signingConfigs {
        release {
            if (resolvedStoreFile != null) {
                storeFile resolvedStoreFile
            }
            storePassword envOrProp('SIGNING_STORE_PASSWORD')
            keyAlias envOrProp('SIGNING_KEY_ALIAS')
            keyPassword envOrProp('SIGNING_KEY_PASSWORD')
            enableV1Signing true
            enableV2Signing true
            enableV3Signing true
            if (this.respondsTo('enableV4Signing')) {
                enableV4Signing true
            }
        }
        debug {
            if (resolvedStoreFile?.exists()) {
                initWith signingConfigs.release
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'minify/proguard-main.pro',
                    'minify/proguard-okhttp.pro',
                    'minify/proguard-retrofit.pro',
                    'minify/proguard-jackson.pro',
                    'minify/proguard-kotlin-reflect.pro',
                    'minify/proguard-kotlin.pro'
        }
        debug {
            signingConfig signingConfigs.debug
            minifyEnabled false
            multiDexEnabled true
            applicationIdSuffix '.debug'
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
    }

    sourceSets {
        main.java.srcDirs += "${projectDir}/src/main/kotlin"
        test.java.srcDirs += "${projectDir}/src/test/kotlin"
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/LICENSE']
        }
    }

    kotlinOptions {
        jvmTarget = "21"
    }

    buildFeatures {
        viewBinding true
        dataBinding true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    ksp {
        arg("room.schemaLocation", "$rootDir/ultrasonic/schemas")
    }

    lint {
        baseline = file("lint-baseline.xml")
        abortOnError true
        warningsAsErrors true
        warning 'ImpliedQuantity'
        disable 'IconMissingDensityFolder', 'VectorPath'
        disable 'MissingTranslation', 'UnusedQuantity', 'MissingQuantity'
        disable 'ObsoleteLintCustomCheck'
        // We manage dependencies on Gitlab with RenovateBot
        disable 'GradleDependency'
        disable 'AndroidGradlePluginVersion'
        textReport true
        checkDependencies true
    }
    namespace 'org.moire.ultrasonic'

}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

dependencies {
    implementation project(':core:domain')
    implementation project(':core:subsonic-api')

    api(libs.picasso) {
        exclude group: "com.android.support"
    }
    implementation libs.transition
    implementation libs.car
    implementation libs.core
    implementation libs.design
    implementation libs.multidex
    implementation libs.roomRuntime
    implementation libs.roomKtx
    implementation libs.viewModelKtx
    implementation libs.constraintLayout
    implementation libs.preferences
    implementation libs.media3common
    implementation libs.media3exoplayer
    implementation libs.media3session
    implementation libs.media3datasource
    implementation libs.media3okhttp
    implementation libs.swipeRefresh
    implementation libs.lifecycleLivedataKtx

    implementation libs.navigationFragment
    implementation libs.navigationUi
    implementation libs.navigationFragmentKtx
    implementation libs.navigationUiKtx
    implementation libs.navigationFeature

    implementation libs.kotlinStdlib
    implementation libs.kotlinxCoroutines
    implementation libs.kotlinxGuava
    implementation libs.koinAndroid
    implementation libs.okhttpLogging
    implementation libs.fastScroll
    implementation libs.colorPickerView
    implementation libs.rxJava
    implementation libs.rxAndroid
    implementation libs.multiType
    implementation libs.gridlayout

    ksp libs.room

    testImplementation libs.kotlinReflect
    testImplementation libs.junit
    testRuntimeOnly libs.junitVintage
    testImplementation libs.kotlinJunit
    testImplementation libs.kluent
    testImplementation libs.mockito
    testImplementation libs.mockitoKotlin
    testImplementation libs.robolectric

    implementation libs.timber
    implementation(libs.media)
    implementation libs.gson

    implementation(libs.kotlinxSerializationJson)
}

